### ISSUE TITLE
Where's the makefile?

### ISSUE THREAD

**Issue by Isak-Evaldsson** [lkildetoft/ICG-sim#1]
A proper c project needs a makefile

**Comment by Isak-Evaldsson** [comment]
And a decent clang-format file

**Comment by lkildetoft** [comment]
only people who don't know C well enough to build the linux kernel from scratch use makefiles

**Comment by Isak-Evaldsson** [comment]
It's quite a challenge to build the Linux kernel without make files since it's its only build system, but well if you like manually compiling a few hundred thousand source files :kr

**Comment by Isak-Evaldsson** [comment]
:)

**Comment by lkildetoft** [comment]
the pros build the linux kernel from ramdisk with bootstrapping enabled to ensure that the kernel matrix is never returned empty, who even uses a build system anyways I build from ramdisk on os/2 warp also this is a duplicate issue
